[tool.poetry]
name = "quickdraws"
version = "1.0.0"
description = "Quickdraws is a software tool for performing Genome-Wide Association Studies (GWAS)"
authors = ["Palamara Lab"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
h5py = "*"
joblib = "*"
numba = "*"
numpy = "<2"
pandas = "*"
pysnptools = { version = "*", extras = ["bgen"] }
scikit_learn = "*"
scipy = "*"
statsmodels = "*"
tqdm = "*"
wandb = "*"
tables = "*"
bitsandbytes = "*"
pybgen = "*"
art = "*"
rhe = "==1.0.0"
torch = "2.*"

[tool.poetry.dev-dependencies]
pip = ">=23"
setuptools = ">=68"

[tool.poetry.scripts]
quickdraws-step-1 = "quickdraws.scripts.quickdraws_step1:main"
quickdraws-step-2 = "quickdraws.scripts.quickdraws_step2:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
