name: Publish to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  publish_wheels:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'PalamaraLab/quickdraws' }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: check python version
        run: |
          poetry run python --version

      - name: install dependencies
        run: |
          poetry install --no-cache

      - name: check disk space
        run: |
          df -h .

      - name: build package
        run: |
          poetry build

      - name: Verify distribution files
        run: ls -l dist/

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
