name: "Test package"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Tests example and packaging
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-24.04"
            python: "3.10"
          - os: "ubuntu-24.04"
            python: "3.12"
          - os: "macos-14"
            python: "3.12"

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: check python version
        run: |
          poetry run python --version

      - name: install python module
        run: |
          poetry install

      - name: run python example
        run: |
          chmod +x run_example.sh
          poetry run ./run_example.sh
        shell: bash

      - name: check dist builds
        run: |
          poetry build
